name: My First GitHub Actions

on: [push]   # or commit
jobs:
  build:
    runs-on: ubuntu-latest  # on machie

    strategy:
      matrix:
        python-version: [3.8, 3.9]  # versions of pipelines

    steps:
    - uses: actions/checkout@v3 #plugin
    - name: Set up Python
      uses: actions/setup-python@v2 #plugin
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
